export const veiculosMock = [
	{
		id: 1,
		placa: "ABC1D23",
		marca: "Toyota",
		modelo: "Corolla",
		favoritado: false,
		descricao: "Sedan médio, ideal para uso urbano e viagens, com bom consumo de combustível e manutenção acessível.",
		ano: 2021,
		tipo: "Carro",
		valorFipe: 98500,
		kmRodados: 62000,
		proximaRevisaoKm: 70000,
		situacaoManutencao: "Em dia",
		combustivel: "Gasolina",
		imagem: "/images/corolla.png"
	},
	{
		id: 2,
		placa: "XYZ9A87",
		marca: "Honda",
		modelo: "Civic",
		favoritado: false,
		ano: 2020,
		tipo: "Carro",
		valorFipe: 103000,
		kmRodados: 78000,
		proximaRevisaoKm: 80000,
		situacaoManutencao: "Próxima",
		combustivel: "Gasolina",
		imagem: "/images/civic.png"
	},
	{
		id: 3,
		placa: "TRK4B22",
		marca: "Volkswagen",
		modelo: "Saveiro",
		favoritado: false,
		ano: 2019,
		tipo: "Utilitário",
		valorFipe: 68000,
		kmRodados: 91000,
		proximaRevisaoKm: 90000,
		situacaoManutencao: "Vencida",
		combustivel: "Gasolina",
		imagem: "/images/saveiro.png"
	},
	{
		id: 4,
		placa: "FRT7C45",
		marca: "Fiat",
		modelo: "Strada",
		favoritado: false,
		ano: 2022,
		tipo: "Utilitário",
		valorFipe: 92000,
		kmRodados: 43000,
		proximaRevisaoKm: 50000,
		situacaoManutencao: "Em dia",
		combustivel: "Gasolina",
		imagem: "/images/strada.png"
	},
	{
		id: 5,
		placa: "VAN2D10",
		marca: "Renault",
		modelo: "Master",
		favoritado: false,
		ano: 2018,
		tipo: "Van",
		valorFipe: 115000,
		kmRodados: 132000,
		proximaRevisaoKm: 130000,
		situacaoManutencao: "Vencida",
		combustivel: "Diesel",
		imagem: "/images/master.png"
	},
	{
		id: 6,
		placa: "BUS8E31",
		marca: "Mercedes-Benz",
		modelo: "Sprinter",
		favoritado: false,
		ano: 2021,
		tipo: "Van",
		valorFipe: 185000,
		kmRodados: 87000,
		proximaRevisaoKm: 90000,
		situacaoManutencao: "Próxima",
		combustivel: "Diesel",
		imagem: "/images/sprinter.png"
	},
	{
		id: 7,
		placa: "CAM5F90",
		marca: "Volvo",
		modelo: "FH 540",
		favoritado: false,
		ano: 2020,
		tipo: "Caminhão",
		valorFipe: 520000,
		kmRodados: 260000,
		proximaRevisaoKm: 270000,
		situacaoManutencao: "Em dia",
		combustivel: "Diesel",
		imagem: "/images/volvo-fh.png"
	},
	{
		id: 8,
		placa: "MBZ3G44",
		marca: "Mercedes-Benz",
		modelo: "Accelo 1016",
		favoritado: false,
		ano: 2017,
		tipo: "Caminhão",
		valorFipe: 210000,
		kmRodados: 310000,
		proximaRevisaoKm: 300000,
		situacaoManutencao: "Vencida",
		combustivel: "Diesel",
		imagem: "/images/accelo.png"
	},
	{
		id: 9,
		placa: "MOT1H55",
		marca: "Honda",
		modelo: "CG 160 Cargo",
		favoritado: false,
		ano: 2023,
		tipo: "Moto",
		valorFipe: 16500,
		kmRodados: 18000,
		proximaRevisaoKm: 20000,
		situacaoManutencao: "Em dia",
		combustivel: "Gasolina",
		imagem: "/images/cg-cargo.png"
	},
	{
		id: 10,
		placa: "ELT6J77",
		marca: "Chevrolet",
		modelo: "Montana",
		favoritado: false,
		ano: 2024,
		tipo: "Utilitário",
		valorFipe: 128000,
		kmRodados: 12000,
		proximaRevisaoKm: 15000,
		situacaoManutencao: "Próxima",
		combustivel: "Gasolina",
		imagem: "/images/montana.png"
	}
];